module.exports = {
  someSidebar: [
    {
      "Getting started": [
        "Getting Started/welcome",
        "Getting Started/install"
      ],
    },
   "Setting/setting-management",
    {
      Trigger: [
        "Trigger/contact-form7",
        "Trigger/eform",
        "Trigger/elementor-form",
        "Trigger/everest-forms",
        "Trigger/fluent-form",
        "Trigger/forminator",
        "Trigger/gravity-forms",
        "Trigger/ninja-forms",
        "Trigger/piotnet-forms",
        "Trigger/user-registration",
        "Trigger/wpforms",
        "Trigger/wsform",
        "Trigger/woocommerce",
      ],
    },
    {
      Actions: [
        "actions/activecampaign",
        "actions/autonami",
        "actions/dropbox",
        "actions/elastic-email",
        "actions/email",
        "actions/encharge",
        "actions/fluentcrm",
        "actions/getgist",
        "actions/google-drive",
        "actions/google-sheet",
        "actions/mailchimp",
        "actions/mailpoet",
        "actions/pods",
        "actions/post-creation",
        "actions/rapidmail",
        "actions/sendinblue",
        "actions/telegram",
        "actions/zohobigin",
        "actions/zohocampaign",
        "actions/zohocrm",
        "actions/zohomarketinghub",
        "actions/zohorecruit",
      ],
    },
    // "Response Management/response-management",
  ],
  changelog: ["changelog/overview", "changelog/prooverview"],
};
