module.exports = {
  someSidebar: [
    {
      "Getting started": [
        "Getting Started/welcome",
        "Getting Started/install"
      ],
    },
   "Setting/setting-management",
   "Integration Action/integration-action",
   "conditional-logic",
    {
      Trigger: [
        "Trigger/amelia",
        "Trigger/beaver-builder",
        "Trigger/bricks",
        "Trigger/brizy",
        "Trigger/contact-form7",
        "Trigger/divi",
        "Trigger/eform",
        "Trigger/elementor-form",
        "Trigger/everest-forms",
        "Trigger/fluent-crm",
        "Trigger/fluent-form",
        "Trigger/fluent-support",
        "Trigger/formidable-forms",
        "Trigger/forminator",
        "Trigger/gravity-forms",
        "Trigger/groundhogg",
        "Trigger/happy-forms",
        "Trigger/jetformbuilder",
        "Trigger/kadence-blocks-form",
        "Trigger/kali-forms",
        "Trigger/mb-frontend-submission",
        "Trigger/met-form",
        "Trigger/ninja-forms",
        "Trigger/piotnet-forms",
        "Trigger/studiocart",
        "Trigger/tutor-lms",
        "Trigger/user-registration",
        "Trigger/webhook",
        "Trigger/woocommerce",
        "Trigger/wp-courseware",
        "Trigger/wpforms",
        "Trigger/wp-post",
        "Trigger/wsform",
      ],
    },
    {
      Actions: [
        "actions/activecampaign",
        "actions/acumbamail",
        "actions/autonami",
        "actions/bitform",
        "actions/dropbox",
        "actions/elastic-email",
        "actions/email",
        "actions/encharge",
        "actions/fluent-support",
        "actions/fluentcrm",
        "actions/freshdesk",
        "actions/getgist",
        "actions/google-calendar",
        "actions/google-drive",
        "actions/google-sheet",
        "actions/groundhogg",
        "actions/hubspot",
        "actions/keap",
        "actions/mailchimp",
        "actions/mailerlite",
        "actions/mailpoet",
        "actions/onedrive",
        "actions/pods",
        "actions/post-creation",
        "actions/rapidmail",
        "actions/registration",
        "actions/sendfox",
        "actions/sendinblue",
        "actions/slack",
        "actions/telegram",
        "actions/trello",
        "actions/tutor-lms",
        "actions/wishlist",
        "actions/woocommerce",
        "actions/wp-courseware",
        "actions/zohocrm",
        "actions/zoho-desk",
        "actions/zohorecruit",
        "actions/zohobigin",
        "actions/zohocampaign",
        "actions/zohomarketinghub",
        "actions/zoom-meeting",
        "actions/zoom-webinar",
        
      ],
    },
    "changelog/overview",
    "bit-integration-feature-request"
  ],
  
  
  
  changelog: ["changelog/overview", "changelog/prooverview"],
};
