module.exports = {
  someSidebar: [
    {
      "Getting started": ["Getting Started/welcome"],
    },
 
   {
      "Contact Form 7": [
        "Contact Form 7/cf7-activecampaign",
        "Contact Form 7/cf7-encharge",
        "Contact Form 7/cf7-rapidmail",
        "Contact Form 7/cf7-mailchimp",
        "Contact Form 7/cf7-telegram",
        "Contact Form 7/cf7-zohocrm",
        "Contact Form 7/cf7-zohobigin",
        "Contact Form 7/cf7-zohorecruit",
        "Contact Form 7/cf7-zohocampaign",
        "Contact Form 7/cf7-zohomarketinghub",
      ],
    },
    {
      "Gravity Forms": [
        "Gravity Forms/gf-activecampaign",
        "Gravity Forms/gf-encharge",
        "Gravity Forms/gf-rapidmail",
        "Gravity Forms/gf-mailchimp",
        "Gravity Forms/gf-telegram",
        "Gravity Forms/gf-zohocrm",
        "Gravity Forms/gf-zohobigin",
        "Gravity Forms/gf-zohorecruit",
        "Gravity Forms/gf-zohocampaign",
        "Gravity Forms/gf-zohomarketinghub",
      ],
    },
    { 
      "WPForms": [
        "WPForms/wpf-activecampaign",
        "WPForms/wpf-encharge",
        "WPForms/wpf-rapidmail",
        "WPForms/wpf-mailchimp",
        "WPForms/wpf-telegram",
        "WPForms/wpf-zohocrm",
        "WPForms/wpf-zohobigin",
        "WPForms/wpf-zohorecruit",
        "WPForms/wpf-zohocampaign",
        "WPForms/wpf-zohomarketinghub",
      ],
    },
    { 
      "Ninja Forms": [
        "Ninja Forms/ninjaf-activecampaign",
        "Ninja Forms/ninjaf-encharge",
        "Ninja Forms/ninjaf-rapidmail",
        "Ninja Forms/ninjaf-mailchimp",
        "Ninja Forms/ninjaf-telegram",
        "Ninja Forms/ninjaf-zohocrm",
        "Ninja Forms/ninjaf-zohobigin",
        "Ninja Forms/ninjaf-zohorecruit",
        "Ninja Forms/ninjaf-zohocampaign",
        "Ninja Forms/ninjaf-zohomarketinghub",
      ],
    },
    { 
      "Fluent Forms": [
        "Fluent Forms/fluentf-activecampaign",
        "Fluent Forms/fluentf-encharge",
        "Fluent Forms/fluentf-rapidmail",
        "Fluent Forms/fluentf-mailchimp",
        "Fluent Forms/fluentf-telegram",
        "Fluent Forms/fluentf-zohocrm",
        "Fluent Forms/fluentf-zohobigin",
        "Fluent Forms/fluentf-zohorecruit",
        "Fluent Forms/fluentf-zohocampaign",
        "Fluent Forms/fluentf-zohomarketinghub",
      ],
    },
    { 
      "WS Form": [
        "WS Form/wsform-activecampaign",
        "WS Form/wsform-encharge",
        "WS Form/wsform-rapidmail",
        "WS Form/wsform-mailchimp",
        "WS Form/wsform-telegram",
        "WS Form/wsform-zohocrm",
        "WS Form/wsform-zohobigin",
        "WS Form/wsform-zohorecruit",
        "WS Form/wsform-zohocampaign",
        "WS Form/wsform-zohomarketinghub",
      ],
    },
    { 
      "Forminator": [
        "Forminator/forminator-activecampaign",
        "Forminator/forminator-encharge",
        "Forminator/forminator-rapidmail",
        "Forminator/forminator-mailchimp",
        "Forminator/forminator-telegram",
        "Forminator/forminator-zohocrm",
        "Forminator/forminator-zohobigin",
        "Forminator/forminator-zohorecruit",
        "Forminator/forminator-zohocampaign",
        "Forminator/forminator-zohomarketinghub",
      ],
    },
    { 
      "eForm": [
        "eForm/eform-activecampaign",
        "eForm/eform-encharge",
        "eForm/eform-rapidmail",
        "eForm/eform-mailchimp",
        "eForm/eform-telegram",
        "eForm/eform-zohocrm",
        "eForm/eform-zohobigin",
        "eForm/eform-zohorecruit",
        "eForm/eform-zohocampaign",
        "eForm/eform-zohomarketinghub",
      ],
    },
    { 
      "Piotnet Forms": [
        "Piotnet Forms/piotnetforms-activecampaign",
        "Piotnet Forms/piotnetforms-encharge",
        "Piotnet Forms/piotnetforms-rapidmail",
        "Piotnet Forms/piotnetforms-mailchimp",
        "Piotnet Forms/piotnetforms-telegram",
        "Piotnet Forms/piotnetforms-zohocrm",
        "Piotnet Forms/piotnetforms-zohobigin",
        "Piotnet Forms/piotnetforms-zohorecruit",
        "Piotnet Forms/piotnetforms-zohocampaign",
        "Piotnet Forms/piotnetforms-zohomarketinghub",
      ],
    },
    // "Response Management/response-management",
  ],
  changelog: ["changelog/overview", "changelog/prooverview"],
};
