name: Merge other brach to master
on:
  push:
    branches:
      - wayes
      - mizan
jobs:
  merge-branch:
    runs-on: ubuntu-latest
    steps:
      
      
      - name: Push
        run:  ${{ steps.myref.outputs.branch }}
    
