name: merge mizan into main

on:
  push:
    branches:
      - mizan

jobs:
  update-cms-master:
    name: Merge master into release after a PR is merged
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: merge
        uses: mtanzi/action-automerge@v1
        id: merge
        with:
          github_token: ${{ github.token }}
          source: 'mizan'
          target: 'main'
          # webhook_url: #if present add the Slack webhook
